name: Test CIRC

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt, clippy
    - uses: Swatinem/rust-cache@v2
    - name: Install cargo-audit
      run: cargo install cargo-audit

    - name: Run checks
      run: |
        cargo check --verbose
        cargo fmt -- --check
        cargo clippy -- -D warnings
        cargo audit

    - name: Run tests
      run: |
        cargo test
        cargo test --release
